FROM node:8.11-alpine

WORKDIR /var/app

RUN apk add --no-cache git && \
    npm install -g @angular/cli

#+ nginx.conf
RUN echo c2VydmVyIHsKICAgIGxpc3RlbiA4MDsKCiAgICBsb2NhdGlvbiAvIHsKICAgICAgICByb290IC92YXIvYXBwOwogICAgICAgIHRyeV9maWxlcyAkdXJpIC9pbmRleC5odG1sOwogICAgfQp9Cg== | base64 -d > /etc/nginx.conf

COPY . /var/app

ARG COMMIT=HEAD

RUN git remote remove origin && \
    git clean -xfd && \
    git reset --hard && \
    git checkout master && \
    git checkout $COMMIT

RUN npm install && \
    npm run build

FROM nginx:1.13.9-alpine

COPY --from=0 /var/app/dist /var/app/
COPY --from=0 /etc/nginx.conf /etc/nginx/conf.d/default.conf

STOPSIGNAL SIGTERM

ENTRYPOINT ["nginx", "-g", "daemon off;"]

# hash=c1e3bfeef1e8cb86195cffe59dea5d7c85c65334
# docker build . -f Dockerfile.demo --build-arg COMMIT=$hash -t demo/ui:$hash
# docker run -p 80:80 demo/ui:$hash
