version: "3.3"

services:
#  tas-gateway:
#    build:
#      context: ./workspace/tas-gateway
#      dockerfile: Dockerfile
#    container_name: tas-gateway
#    volumes:
#     - ./workspace/tas-gateway/nginx.conf:/etc/nginx/conf.d/default.conf
#    ports:
#     - 80:80
#     - 3000:3000
#     - 3001:3001
#     - 8080:8080
#     - 8088:8088
#     - 9200:9200
#     - 8081:8081
#     - 4369:4369
#     - 5672:5672
#     - 5671:5671

  jboss-base:
    build: 
      context: ./
      dockerfile: dkr/DockerFileBaseOS.txt 
    container_name: jboss/base:latest 
#    network_mode: service:tas-gateway
#    depends_on:
#     - tas-gateway

  jboss-base-jdk-8:
    build: 
      context: ./
      dockerfile: dkr/DockerFileJDK8.txt 
    container_name: jboss/base-jdk:8
#    network_mode: service:tas-gateway
#    depends_on:
#     - tas-gateway

#  jboss-wildfly:
#    build:
#      context: ./
#      dockerfile: dkr/DockerFileWildFly10.txt
#    container_name: jboss/wildfly
##    network_mode: service:tas-gateway
##    depends_on:
##     - tas-gateway

  jboss-drools-workbench:
    build: 
      context: ./
      dockerfile: dkr/DockerFileDroolsWorkbench.txt 
    container_name: jboss/drools-workbench
#    network_mode: service:tas-gateway
#    depends_on:
#     - tas-gateway

  jboss-drools-workbench-showcase:
    build: 
      context: ./
      dockerfile: dkr/DockerFileDroolsWorkbenchShowcase.txt 
    container_name: jboss/drools-workbench-showcase
#    network_mode: service:tas-gateway
#    depends_on:
#     - tas-gateway


  jboss-kie-server:
    build: 
      context: ./
      dockerfile: dkr/DockerFileKIE-Server.txt 
    container_name: jboss/kie-server
#    network_mode: service:tas-gateway
#    depends_on:
#     - tas-gateway

  jboss-kie-server-showcase:
    build: 
      context: ./
      dockerfile: dkr/DockerFileKIE-ServerShowcase.txt 
    container_name: jboss/kie-server-showcase
#    network_mode: service:tas-gateway
#    depends_on:
#     - tas-gateway



  # tas-fhir:
  # tas-relay:
  #   build: 
  #     context: ./workspace/tas-relay/src
  #     dockerfile: Dockerfile
  #   container_name: tas-relay
  #   volumes:
  #    - ./workspace/tas-relay/src:/var/app
  #   environment:
  #     - "DEVELOPMENT_MODE=true"
  #     - "PORT=3000"
  #     - "LIVE_HTTP=true"
  #     - "DEBUG=http,api"
  #   network_mode: service:tas-gateway
  #   depends_on:
  #       - tas-gateway

  # tas-queue:
  #   image: rabbitmq:3.7.3-alpine
  #   network_mode: service:tas-gateway
  #   depends_on:
  #       - tas-gateway

  #tascore-api:
  #  build:
  #    context: ./workspace/tascore-api/src
  #    dockerfile: Dockerfile.dev
  #  container_name: tascore-api
  #  volumes:
  #    - ./workspace/tascore-api/src:/var/app
  #    - ./workspace/tascore-api-logs:/var/log/tas
  #  # cap_add:
  #  #   - net_bind_service
  #  # cap_drop:
  #  #   - ALL
  ###  environment:
  #    - "PORT=3001"
  #    - "DEBUG=api,api-internal,azure,data,fs,core,memory,webclient,errors"
  #    - "TAS_QUEUE_ADDRESS=amqp://192.168.100.10"
  #    - "TAS_ENABLE_HTTP=true"
  #    - "TAS_FILESYSTEM_DATA_ROOT=/var/log/tas"
  #    - "TAS_PROVIDERS=LOGGING:fs,CONFIG:azure"
  #    - "TAS_AZURE_STORAGE_NAME=tasstorage01"
  #    - "TAS_AZURE_STORAGE_KEY=qv8Tkil0Q51dXK7GZS+ehia/kw+omMy7j4QiP2IeWtW6dD+jJ3CYLux9dNdXdl7wsvr3Ew9XLPiKsER06MnDWQ=="
  #    # - "TAS_ELASTICSEARCH_CONNECTION_STRING=http://127.0.0.1:9200"
  #  network_mode: service:tas-gateway
  #  depends_on:
  #      - tas-gateway

  # tas-reporting:
  #   build: ./workspace/reporting
  #   container_name: tas-reporting
  #   network_mode: service:tas-gateway
  #   depends_on:
  #       - tas-gateway

  # tas-fhir:
  #   build:
  #     context: ./workspace/fhir
  #     dockerfile: VA-FHIR-Server/Dockerfile
  #   container_name: tas-fhir

  # tas-elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
  #   container_name: tas-elasticsearch
  #   network_mode: service:tas-gateway
  #   environment:
  #    - "xpack.security.enabled=false"
  #    - "discovery.type=single-node"
  #   depends_on:
  #       - tas-gateway

#  tascore-ui:
#    build: 
#      context: ./workspace/tascore-ui
#      dockerfile: Dockerfile
#    container_name: tascore-ui
#    volumes:
#      - ./workspace/tascore-ui:/var/app
#    network_mode: service:tas-gateway
#    depends_on:
#        - tas-gateway

  # sb:
  #   build:
  #     context: ./workspace/sb/src
  #     dockerfile: Dockerfile.dev
  #   container_name: sb
  #   volumes:
  #     - ./workspace/sb/src:/var/app
  #   # cap_add:
  #   #   - net_bind_service
  #   # cap_drop:
  #   #   - ALL
  #   environment:
  #     - "PORT=3001"
  #     - "DEBUG=api,sbtest,api-internal,amqp,azure,data,fs,core,memory,webclient,errors"
  #     - "TAS_QUEUE_ADDRESS=amqp://192.168.100.10"
  #     - "TAS_ENABLE_HTTP=true"
  #     - "TAS_FILESYSTEM_DATA_ROOT=/var/log/tas"
  #     - "TAS_PROVIDERS=LOGGING:fs,CONFIG:azure"
  #     - "TAS_AZURE_STORAGE_NAME=tasstorage01"
  #     - "TAS_AZURE_STORAGE_KEY=qv8Tkil0Q51dXK7GZS+ehia/kw+omMy7j4QiP2IeWtW6dD+jJ3CYLux9dNdXdl7wsvr3Ew9XLPiKsER06MnDWQ=="
  #     # - "TAS_ELASTICSEARCH_CONNECTION_STRING=http://127.0.0.1:9200"
  #   network_mode: service:tas-gateway
  #   depends_on:
  #       - tas-queue
