version: "3.3"

services:
  tas-nginx:
    build: 
      context: ./workspace
      dockerfile: Dockerfile.nginx
    container_name: tas-nginx
    volumes:
     - ./workspace/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - 80:80
     - 3000:3000
     - 3001:3001
     - 8080:8080
     - 8088:8088
     - 9200:9200
     - 8081:8081
     
  tas-relay:
    build: 
      context: ./workspace/tas-relay/src
      dockerfile: Dockerfile
    container_name: tas-relay
    volumes:
     - ./workspace/tas-relay/src:/var/app
    environment:
      - "DEVELOPMENT_MODE=true"
      - "PORT=3000"
      - "LIVE_HTTP=true"
      - "DEBUG=http,api"
    network_mode: service:tas-nginx
    depends_on:
        - tas-nginx

  tascore-api:
    build: ./workspace/tascore-api/src
    container_name: tascore-api
    volumes:
     - ./workspace/tascore-api/src:/var/app
    environment:
      - "PORT=3001"
      - "TAS_FILESYSTEM_DATA_ROOT=/var/log/tas"
      - "DEBUG=api,api-internal,data,fs,core,memory,webclient"
      - "LIVE_HTTP=true"
      - "TAS_PROVIDER_LOGGING=fs"
      - "TAS_PROVIDER_CONFIG=azure"
      - "TAS_AZURE_STORAGE_NAME=tasstorage01"
      - "TAS_AZURE_STORAGE_KEY=IM+4OtpmRgAd2XXIqrRYOrR5SM2rPhCNDFhLF52maDAk4nMchaPohrwoOZrAwlIvT2jAzU0Nynq+9BF9Lr+PUw=="
      - "TAS_ELASTICSEARCH_CONNECTION_STRING=http://127.0.0.1:9200"
      - "TAS_HAPI_FHIR_URL=http://127.0.0.1:8080/VA-FHIR-Server/fhir"
    network_mode: service:tas-nginx
    depends_on:
        - tas-nginx

  # tas-reporting:
  #   build: ./workspace/reporting
  #   container_name: tas-reporting
  #   network_mode: service:tas-nginx
  #   depends_on:
  #       - tas-nginx

  # tas-fhir:
  #   build:
  #     context: ./workspace/fhir
  #     dockerfile: VA-FHIR-Server/Dockerfile
  #   container_name: tas-fhir
  #   network_mode: service:tas-nginx
  #   depends_on:
  #       - tas-nginx

  # tas-elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.1.3
  #   container_name: tas-elasticsearch
  #   network_mode: service:tas-nginx
  #   environment:
  #    - "xpack.security.enabled=false"
  #    - "discovery.type=single-node"
  #   depends_on:
  #       - tas-nginx

  tascore-ui:
    build: 
      context: ./workspace/tascore-ui
      dockerfile: Dockerfile
    container_name: tascore-ui
    volumes:
      - ./workspace/tascore-ui:/var/app
    network_mode: service:tas-nginx
    depends_on:
        - tas-nginx

